# Generated by Django 4.1.5 on 2023-03-17 18:50

from django.db import migrations, models

import apps.store.models.product


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
    ]
