# Generated by Django 4.1.5 on 2023-03-26 19:57

from django.db import migrations, models

import apps.store.models.users


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_userclient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclient",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userclient",
            name="maximum_credit_value",
            field=models.FloatField(default=400, verbose_name="Maximun credit: "),
        ),
        migrations.AddField(
            model_name="userclient",
            name="remaining_credit",
            field=models.FloatField(default=400, verbose_name="Remaining credit: "),
        ),
    ]
