# Generated by Django 4.1.5 on 2023-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_userclient_image_userclient_maximum_credit_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userclient",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
